### ISSUE TITLE
Create history of discount price

### ISSUE THREAD

**Issue by jducobu** [simplcommerce/SimplCommerce#380] opened 2018-01-27 16:21 UTC
Denormalize discount data in a table with 1:n relationship between product and discount

**Comment by alessalessio** [comment] 2018-03-21 16:40
Are you talking about dbo.Catalog_Product ? Do you want to move the SpecialPrice columns into a separate table and add a foreign key to the active discount ?

**Comment by jducobu** [comment] 2018-03-22 14:07
Exactely! Add also datefrom and dateto to the table perhaps

**Comment by thiennn** [comment] 2018-04-05 15:17
So it duplicate of #286

**Closed by thiennn** 2018-04-05 15:17 UTC
