### ISSUE TITLE
Category Filter with SubCategories on CategoryDetail Page

### ISSUE THREAD

**Issue by unencode** [simplcommerce/SimplCommerce#865] opened 2020-01-31 02:34 UTC
Is there a way to show this category filter with sub categories on the CategoryDetail page?

Like it was done for the search page here: https://github.com/simplcommerce/SimplCommerce/issues/491

**Comment by thiennn** [comment] 2020-03-01 15:49
I think it's possible, will look in to this soon

**Comment by jducobu** [comment] 2020-03-03 18:19
duplicate of #546

**Comment by fhebel** [comment] 2020-04-05 20:55
Here's my proposal:

[diff_SimplCommerce_issue_865.patch.txt](https://github.com/simplcommerce/SimplCommerce/files/4434868/diff_SimplCommerce_issue_865.patch.txt)

**Comment by fhebel** [comment] 2020-04-11 22:40
And here the localization of the breadcrumbs:

[diff_SimplCommerce_issue_865_breadcrumb_localization.patch.txt](https://github.com/simplcommerce/SimplCommerce/files/4465579/diff_SimplCommerce_issue_865_breadcrumb_localization.patch.txt)

**Comment by thiennn** [comment] 2020-05-04 00:06
Thank @fhebel

**Closed by thiennn** 2020-05-04 00:06 UTC
