### ISSUE TITLE
Categories suffering to circular nesting resulting in 100% CPU load and site brick

### ISSUE THREAD

**Issue by Xeevis** [simplcommerce/SimplCommerce#356] opened 2018-01-14 23:11 UTC
It's possible to set for parent it's child's child as parent which leads to a nasty CPU burn scenario and site turning unresponsive.

**Steps to reproduce:**
1) Create new categories A, AA, AAA
2) Set A as parent of AA
3) Set AA as parent of AAA
4) Set AAA as parent of A

To preserve spacetime continuum, It shouldn't be possible to assign any descendant as parent to a parent.

**Comment by thiennn** [comment] 2018-01-15 07:56
Duplicate of #35

**Closed by thiennn** 2018-01-15 07:56 UTC
